version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=common

  postgres1:
    container_name: postgres1
    image: postgres:latest
    ports:
      - '5433:5432'
    volumes:
      - /data/postgres:/data/postgres
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=T-1fe1e39e-4015-4303-a719-6c91d32dd1aa
